### ISSUE TITLE
Have ability to keep libraries in local build. 

### ISSUE THREAD

**Issue by sfeller** [Aqueti/mongoAPI#1]

**Comment by camerongivler** [comment]
When is this an issue?  Installing MongoAPI in a super build does this

**Comment by sfeller** [comment]
Not sure why, but putting it on a clean machine, it was looking for the mongo-cxx drivers in /usr/local. I'll check again tonight.

**Comment by camerongivler** [comment]
Interesting.  I just built it on my machine and /usr/local was clean before and after.  Keep me updated.  CMakeLists.txt does not specify a hard path to an install directory so I'm not sure why it would be looking there

**Comment by camerongivler** [comment]
Make sure you're running it as a SuperBuild.  Otherwise, it will look in /usr/local for mongo-cxx-driver

**Comment by sfeller** [comment]
Ah. Just to be clear, when I install mongoapi by itself, I need super build. It should work?

Sent using OWA for iPhone
________________________________

**Comment by camerongivler** [comment]
Yes it should work with superbuild.  Without superbuild you need to have installed the dependencies separately.

**Comment by sfeller** [comment]
I like easy fixes. I'll check it out tonight.

Sent using OWA for iPhone
________________________________

**Comment by sfeller** [comment]
Still a problem. Had issues with default install. Fixed by changing JSONBOX to JsonBox. Not sure if this is a bug I introduced. However, install fails with respect to larger systems due the inability of the MongoAPI to support "make install"

**Comment by camerongivler** [comment]
That’s very odd.  In FindJsonBox.cmake, JSONBOX is capital, so I would think making it lower case would break it…

I haven’t tested installing mongoAPI because I thought with SuperBuild we wouldn’t need it. I can work on that after finals week when I start full time.

Cameron

**Comment by sfeller** [comment]
Works with Russell's fix in mongoInstall2 branch. Will merge into main branch one at least minimal database functionality is in place.
