### ISSUE TITLE
V2: error while loading shared libraries: libbsoncxx.so._noabi

### ISSUE THREAD

**Issue by alxstep** [Aqueti/mongoAPI#3]
VERSION: mongo/15

Steps:
- Start V2

Issue:
V2 can't be started

Log:
V2: error while loading shared libraries: libbsoncxx.so._noabi: cannot open shared object file: No such file or directory

**Comment by uberferg** [comment]
Tagging @camerongivler because he's the one working on fixing this build issue.

**Comment by camerongivler** [comment]
Try it out now @alxstep

**Comment by alxstep** [comment]
RESULT: ANOTHER ERROR OCCURRED
VERSION: mongo/17

Steps:
- Start V2

Issue:
V2 can't be started

API log:
createIndex: No suitable servers found: `serverSelectionTimeoutMS` expired: [connection refused calling ismaster on '127.0.0.1:27017']: generic server error

V2 log:
1510172013885166: StorageManager(0): CRITICAL_ERROR: StorageManager.cpp::StorageManager: 79: Failed to create session index on acos container collection, loading speed may be abysmal

**Comment by camerongivler** [comment]
@uberferg Somewhere we need to document how to install mongo properly.

**Comment by camerongivler** [comment]
@alxstep This is a different issue.  It is due to mongo not being installed.

**Comment by alxstep** [comment]
@camerongivler yes, I know. But all this issues occur when I'm trying to start V2. So it seems reasonable to resolved all of them inside one ticket

**Comment by uberferg** [comment]
Commit b17e16df3f1662a07f3469203ca3f12bcfce647e of the mongoAPI master branch now has updated instructions for installing MongoDB 3.2 in the README.

@alxstep following these instructions should get these problems fixed.

**Comment by alxstep** [comment]
RESULT: PASS
VERSION: mongo/20

Steps:
- Start V2

No error occurred
